version: '2'

services:

  dms:
    image: andrglo/everest:12.20.2
    hostname: koa-swagger-router
    command: tail -f /dev/null
    working_dir: /root/koa-swagger-router
    volumes:
      - ./docker_fish_history:/root/.config/fish/fish_history
      - .:/root/koa-swagger-router
    environment:
      - NODE_ENV=test
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres
    restart: always

  postgres:
      image: postgres:12.2-alpine
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      restart: always


