swagger: "2.0"
info:
  contact: {}
  license: {}
produces:
   - application/json
   - text/plain; charset=utf-8
schemes:
  - http
securityDefinitions:
  apiKey:
    type: apiKey
    name: key
    in: header
basePath: \
host: localhost

paths: {}

definitions: {}



